import { Metadata } from "next";
import "../../styles/global.css";
import { Layout, useCtx } from "ui";

export const metadata: Metadata = {
  title: "Geonet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout
          key={"MORELATEST"}
          onMobileDrawer={true}
          drawer={{
            color: "gray",
            menu: [
              { label: "Hai", route: "hai" },
              { label: "Hai", route: "hai" },
            ],
          }}
          navbar={{
            color: "gray",
          }}
          footer={{
            color: "gray",
          }}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
